export const PRESET_SELECTED = 'PRESET_SELECTED';
export const TOGGLE_AUTO_SAVE = 'TOGGLE_AUTO_SAVE';
export const SET_DEFAULT_IN_USE = 'SET_DEFAULT_IN_USE';
export const UNSET_DEFAULT_IN_USE = 'UNSET_DEFAULT_IN_USE';
export const ADD_NEW_PRESET = 'ADD_NEW_PRESET';
export const DELETE_PRESET = 'DELETE_PRESET';
export const UPDATE_PARAMS = 'UPDATE_PARAMS';
export const GET_COMP_PRESETS = 'GET_COMP_PRESETS';
export const GET_EQ_PRESETS = 'GET_EQ_PRESETS';
export const GET_PRESETS = 'GET_PRESETS';
export const REPORT_ERROR = 'REPORT_ERROR';
export const IS_LOADING = 'IS_LOADING';

